odroidgoa-uboot-config

########################################################################
# Telmi-os 0.3.2 -- DTB ArkOS4Clone (Select-DTB.bat). LF only (no CR).
# Pas d'uInitrd ArkOS. Defaut : rk3326-r36s-v30-linux.dtb
########################################################################

# Boot Arguments
setenv bootargs "root=/dev/mmcblk0p2 rootwait rw fsck.mode=skip net.ifnames=0 fbcon=map:9 vt.global_cursor_default=0 console=/dev/ttyFIQ0 quiet loglevel=3 nosplash plymouth.enable=0 consoleblank=0 systemd.show_status=false max_cpufreq=1296 boot_cpufreq=1248 max_gpufreq=520 max_ddrfreq=666"

# Booting
setenv loadaddr "0x02000000"
setenv dtb_loadaddr "0x01f00000"

load mmc 1:1 ${loadaddr} Image
load mmc 1:1 ${dtb_loadaddr} rk3326-r36s-v30-linux.dtb

booti ${loadaddr} - ${dtb_loadaddr}
